// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.proto

package gnmi_ext

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExtensionID int32

const (
	ExtensionID_EID_UNSET        ExtensionID = 0
	ExtensionID_EID_EXPERIMENTAL ExtensionID = 999
)

var ExtensionID_name = map[int32]string{
	0:   "EID_UNSET",
	999: "EID_EXPERIMENTAL",
}

var ExtensionID_value = map[string]int32{
	"EID_UNSET":        0,
	"EID_EXPERIMENTAL": 999,
}

func (x ExtensionID) String() string {
	return proto.EnumName(ExtensionID_name, int32(x))
}

func (ExtensionID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{0}
}

type Extension struct {
	// Types that are valid to be assigned to Ext:
	//	*Extension_RegisteredExt
	//	*Extension_MasterArbitration
	Ext                  isExtension_Ext `protobuf_oneof:"ext"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Extension) Reset()         { *m = Extension{} }
func (m *Extension) String() string { return proto.CompactTextString(m) }
func (*Extension) ProtoMessage()    {}
func (*Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{0}
}

func (m *Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extension.Unmarshal(m, b)
}
func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extension.Marshal(b, m, deterministic)
}
func (m *Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extension.Merge(m, src)
}
func (m *Extension) XXX_Size() int {
	return xxx_messageInfo_Extension.Size(m)
}
func (m *Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_Extension proto.InternalMessageInfo

type isExtension_Ext interface {
	isExtension_Ext()
}

type Extension_RegisteredExt struct {
	RegisteredExt *RegisteredExtension `protobuf:"bytes,1,opt,name=registered_ext,json=registeredExt,proto3,oneof"`
}

type Extension_MasterArbitration struct {
	MasterArbitration *MasterArbitration `protobuf:"bytes,2,opt,name=master_arbitration,json=masterArbitration,proto3,oneof"`
}

func (*Extension_RegisteredExt) isExtension_Ext() {}

func (*Extension_MasterArbitration) isExtension_Ext() {}

func (m *Extension) GetExt() isExtension_Ext {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *Extension) GetRegisteredExt() *RegisteredExtension {
	if x, ok := m.GetExt().(*Extension_RegisteredExt); ok {
		return x.RegisteredExt
	}
	return nil
}

func (m *Extension) GetMasterArbitration() *MasterArbitration {
	if x, ok := m.GetExt().(*Extension_MasterArbitration); ok {
		return x.MasterArbitration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Extension) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Extension_RegisteredExt)(nil),
		(*Extension_MasterArbitration)(nil),
	}
}

type RegisteredExtension struct {
	Id                   ExtensionID `protobuf:"varint,1,opt,name=id,proto3,enum=gnmi_ext.ExtensionID" json:"id,omitempty"`
	Msg                  []byte      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisteredExtension) Reset()         { *m = RegisteredExtension{} }
func (m *RegisteredExtension) String() string { return proto.CompactTextString(m) }
func (*RegisteredExtension) ProtoMessage()    {}
func (*RegisteredExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{1}
}

func (m *RegisteredExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredExtension.Unmarshal(m, b)
}
func (m *RegisteredExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredExtension.Marshal(b, m, deterministic)
}
func (m *RegisteredExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredExtension.Merge(m, src)
}
func (m *RegisteredExtension) XXX_Size() int {
	return xxx_messageInfo_RegisteredExtension.Size(m)
}
func (m *RegisteredExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredExtension.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredExtension proto.InternalMessageInfo

func (m *RegisteredExtension) GetId() ExtensionID {
	if m != nil {
		return m.Id
	}
	return ExtensionID_EID_UNSET
}

func (m *RegisteredExtension) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MasterArbitration struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ElectionId           *Uint128 `protobuf:"bytes,2,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterArbitration) Reset()         { *m = MasterArbitration{} }
func (m *MasterArbitration) String() string { return proto.CompactTextString(m) }
func (*MasterArbitration) ProtoMessage()    {}
func (*MasterArbitration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{2}
}

func (m *MasterArbitration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterArbitration.Unmarshal(m, b)
}
func (m *MasterArbitration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterArbitration.Marshal(b, m, deterministic)
}
func (m *MasterArbitration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterArbitration.Merge(m, src)
}
func (m *MasterArbitration) XXX_Size() int {
	return xxx_messageInfo_MasterArbitration.Size(m)
}
func (m *MasterArbitration) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterArbitration.DiscardUnknown(m)
}

var xxx_messageInfo_MasterArbitration proto.InternalMessageInfo

func (m *MasterArbitration) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *MasterArbitration) GetElectionId() *Uint128 {
	if m != nil {
		return m.ElectionId
	}
	return nil
}

type Uint128 struct {
	High                 uint64   `protobuf:"varint,1,opt,name=high,proto3" json:"high,omitempty"`
	Low                  uint64   `protobuf:"varint,2,opt,name=low,proto3" json:"low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uint128) Reset()         { *m = Uint128{} }
func (m *Uint128) String() string { return proto.CompactTextString(m) }
func (*Uint128) ProtoMessage()    {}
func (*Uint128) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{3}
}

func (m *Uint128) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint128.Unmarshal(m, b)
}
func (m *Uint128) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint128.Marshal(b, m, deterministic)
}
func (m *Uint128) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint128.Merge(m, src)
}
func (m *Uint128) XXX_Size() int {
	return xxx_messageInfo_Uint128.Size(m)
}
func (m *Uint128) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint128.DiscardUnknown(m)
}

var xxx_messageInfo_Uint128 proto.InternalMessageInfo

func (m *Uint128) GetHigh() uint64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Uint128) GetLow() uint64 {
	if m != nil {
		return m.Low
	}
	return 0
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82dd429820efefe, []int{4}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("gnmi_ext.ExtensionID", ExtensionID_name, ExtensionID_value)
	proto.RegisterType((*Extension)(nil), "gnmi_ext.Extension")
	proto.RegisterType((*RegisteredExtension)(nil), "gnmi_ext.RegisteredExtension")
	proto.RegisterType((*MasterArbitration)(nil), "gnmi_ext.MasterArbitration")
	proto.RegisterType((*Uint128)(nil), "gnmi_ext.Uint128")
	proto.RegisterType((*Role)(nil), "gnmi_ext.Role")
}

func init() {
	proto.RegisterFile("github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.proto", fileDescriptor_c82dd429820efefe)
}

var fileDescriptor_c82dd429820efefe = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x5d, 0x4b, 0x02, 0x41,
	0x14, 0xf5, 0x63, 0xcb, 0xbc, 0xe6, 0xb2, 0xde, 0x30, 0x84, 0x08, 0x62, 0x21, 0x88, 0x1e, 0x5c,
	0x5a, 0x5f, 0x7c, 0x35, 0xdc, 0x70, 0x41, 0x25, 0x26, 0x85, 0xde, 0x16, 0x75, 0xa7, 0x75, 0x68,
	0x77, 0x46, 0xc6, 0x89, 0xfc, 0x49, 0xfd, 0xb3, 0xfe, 0x46, 0xcc, 0xa0, 0xbb, 0x52, 0xbd, 0x9d,
	0x7b, 0xee, 0x99, 0x73, 0xcf, 0x61, 0xa0, 0x9f, 0x30, 0xb5, 0xfe, 0x58, 0x76, 0x57, 0x22, 0xf3,
	0xc4, 0x86, 0xf2, 0x95, 0xe0, 0x6f, 0x2c, 0xf1, 0x12, 0x9e, 0x31, 0x6f, 0x23, 0x85, 0x12, 0x06,
	0x46, 0x74, 0xa7, 0x72, 0xd0, 0x35, 0x3c, 0x9e, 0x1d, 0x66, 0xf7, 0xab, 0x0c, 0xf5, 0x60, 0xa7,
	0x28, 0xdf, 0x32, 0xc1, 0xf1, 0x09, 0x6c, 0x49, 0x13, 0xb6, 0x55, 0x54, 0xd2, 0x58, 0xef, 0x3b,
	0xe5, 0x9b, 0xf2, 0x5d, 0xc3, 0xbf, 0xee, 0xe6, 0x06, 0x24, 0xdf, 0xe7, 0xcf, 0x46, 0x25, 0xd2,
	0x94, 0xc7, 0x34, 0x8e, 0x01, 0xb3, 0x85, 0x1e, 0xa3, 0x85, 0x5c, 0x32, 0x25, 0x17, 0x8a, 0x09,
	0xde, 0xa9, 0x18, 0xaf, 0xab, 0xc2, 0x6b, 0x62, 0x34, 0x83, 0x42, 0x32, 0x2a, 0x91, 0x56, 0xf6,
	0x9b, 0x7c, 0x3c, 0x81, 0xaa, 0x8e, 0x3a, 0x85, 0x8b, 0x7f, 0x8e, 0xe3, 0x2d, 0x54, 0x58, 0x6c,
	0x72, 0xda, 0x7e, 0xbb, 0xf0, 0xce, 0x05, 0xe1, 0x90, 0x54, 0x58, 0x8c, 0x0e, 0x54, 0xb3, 0x6d,
	0x62, 0x32, 0x9c, 0x13, 0x0d, 0xdd, 0x77, 0x68, 0xfd, 0x09, 0x80, 0x2e, 0x58, 0x52, 0xa4, 0x74,
	0xdf, 0xdb, 0x3e, 0xea, 0x2d, 0x52, 0x4a, 0xcc, 0x0e, 0x7d, 0x68, 0xd0, 0x94, 0xae, 0xb4, 0x3e,
	0x62, 0xf1, 0xbe, 0x56, 0xab, 0x90, 0xce, 0x19, 0x57, 0x0f, 0x7e, 0x9f, 0xc0, 0x41, 0x15, 0xc6,
	0xae, 0x07, 0xb5, 0x3d, 0x8d, 0x08, 0xd6, 0x9a, 0x25, 0x6b, 0x73, 0xc2, 0x22, 0x06, 0xeb, 0x74,
	0xa9, 0xf8, 0x34, 0x56, 0x16, 0xd1, 0xd0, 0xbd, 0x04, 0x4b, 0x9f, 0x44, 0x3b, 0xaf, 0x57, 0xd7,
	0x3d, 0xee, 0x7b, 0xd0, 0x38, 0xaa, 0x86, 0x4d, 0xa8, 0x07, 0xe1, 0x30, 0x9a, 0x4f, 0x5f, 0x82,
	0x99, 0x53, 0xc2, 0x36, 0x38, 0x7a, 0x0c, 0x5e, 0x9f, 0x03, 0x12, 0x4e, 0x82, 0xe9, 0x6c, 0x30,
	0x76, 0xbe, 0x6b, 0xcb, 0x53, 0xf3, 0xed, 0xbd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x43,
	0xfb, 0x5d, 0x32, 0x02, 0x00, 0x00,
}
