// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/gnmi/proto/gnmi/gnmi.proto

package gnmi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	any "github.com/golang/protobuf/ptypes/any"
	gnmi_ext "gnmi_ext"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Encoding int32

const (
	Encoding_JSON      Encoding = 0
	Encoding_BYTES     Encoding = 1
	Encoding_PROTO     Encoding = 2
	Encoding_ASCII     Encoding = 3
	Encoding_JSON_IETF Encoding = 4
)

var Encoding_name = map[int32]string{
	0: "JSON",
	1: "BYTES",
	2: "PROTO",
	3: "ASCII",
	4: "JSON_IETF",
}

var Encoding_value = map[string]int32{
	"JSON":      0,
	"BYTES":     1,
	"PROTO":     2,
	"ASCII":     3,
	"JSON_IETF": 4,
}

func (x Encoding) String() string {
	return proto.EnumName(Encoding_name, int32(x))
}

func (Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{0}
}

type SubscriptionMode int32

const (
	SubscriptionMode_TARGET_DEFINED SubscriptionMode = 0
	SubscriptionMode_ON_CHANGE      SubscriptionMode = 1
	SubscriptionMode_SAMPLE         SubscriptionMode = 2
)

var SubscriptionMode_name = map[int32]string{
	0: "TARGET_DEFINED",
	1: "ON_CHANGE",
	2: "SAMPLE",
}

var SubscriptionMode_value = map[string]int32{
	"TARGET_DEFINED": 0,
	"ON_CHANGE":      1,
	"SAMPLE":         2,
}

func (x SubscriptionMode) String() string {
	return proto.EnumName(SubscriptionMode_name, int32(x))
}

func (SubscriptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{1}
}

type SubscriptionList_Mode int32

const (
	SubscriptionList_STREAM SubscriptionList_Mode = 0
	SubscriptionList_ONCE   SubscriptionList_Mode = 1
	SubscriptionList_POLL   SubscriptionList_Mode = 2
)

var SubscriptionList_Mode_name = map[int32]string{
	0: "STREAM",
	1: "ONCE",
	2: "POLL",
}

var SubscriptionList_Mode_value = map[string]int32{
	"STREAM": 0,
	"ONCE":   1,
	"POLL":   2,
}

func (x SubscriptionList_Mode) String() string {
	return proto.EnumName(SubscriptionList_Mode_name, int32(x))
}

func (SubscriptionList_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{12, 0}
}

type UpdateResult_Operation int32

const (
	UpdateResult_INVALID UpdateResult_Operation = 0
	UpdateResult_DELETE  UpdateResult_Operation = 1
	UpdateResult_REPLACE UpdateResult_Operation = 2
	UpdateResult_UPDATE  UpdateResult_Operation = 3
)

var UpdateResult_Operation_name = map[int32]string{
	0: "INVALID",
	1: "DELETE",
	2: "REPLACE",
	3: "UPDATE",
}

var UpdateResult_Operation_value = map[string]int32{
	"INVALID": 0,
	"DELETE":  1,
	"REPLACE": 2,
	"UPDATE":  3,
}

func (x UpdateResult_Operation) String() string {
	return proto.EnumName(UpdateResult_Operation_name, int32(x))
}

func (UpdateResult_Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{19, 0}
}

type GetRequest_DataType int32

const (
	GetRequest_ALL         GetRequest_DataType = 0
	GetRequest_CONFIG      GetRequest_DataType = 1
	GetRequest_STATE       GetRequest_DataType = 2
	GetRequest_OPERATIONAL GetRequest_DataType = 3
)

var GetRequest_DataType_name = map[int32]string{
	0: "ALL",
	1: "CONFIG",
	2: "STATE",
	3: "OPERATIONAL",
}

var GetRequest_DataType_value = map[string]int32{
	"ALL":         0,
	"CONFIG":      1,
	"STATE":       2,
	"OPERATIONAL": 3,
}

func (x GetRequest_DataType) String() string {
	return proto.EnumName(GetRequest_DataType_name, int32(x))
}

func (GetRequest_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{20, 0}
}

type Notification struct {
	Timestamp            int64     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Prefix               *Path     `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Alias                string    `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Update               []*Update `protobuf:"bytes,4,rep,name=update,proto3" json:"update,omitempty"`
	Delete               []*Path   `protobuf:"bytes,5,rep,name=delete,proto3" json:"delete,omitempty"`
	Atomic               bool      `protobuf:"varint,6,opt,name=atomic,proto3" json:"atomic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Notification) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Notification) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Notification) GetUpdate() []*Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *Notification) GetDelete() []*Path {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Notification) GetAtomic() bool {
	if m != nil {
		return m.Atomic
	}
	return false
}

type Update struct {
	Path                 *Path       `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                *Value      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Deprecated: Do not use.
	Val                  *TypedValue `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	Duplicates           uint32      `protobuf:"varint,4,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{1}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

// Deprecated: Do not use.
func (m *Update) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Update) GetVal() *TypedValue {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Update) GetDuplicates() uint32 {
	if m != nil {
		return m.Duplicates
	}
	return 0
}

type TypedValue struct {
	// Types that are valid to be assigned to Value:
	//	*TypedValue_StringVal
	//	*TypedValue_IntVal
	//	*TypedValue_UintVal
	//	*TypedValue_BoolVal
	//	*TypedValue_BytesVal
	//	*TypedValue_FloatVal
	//	*TypedValue_DecimalVal
	//	*TypedValue_LeaflistVal
	//	*TypedValue_AnyVal
	//	*TypedValue_JsonVal
	//	*TypedValue_JsonIetfVal
	//	*TypedValue_AsciiVal
	//	*TypedValue_ProtoBytes
	Value                isTypedValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TypedValue) Reset()         { *m = TypedValue{} }
func (m *TypedValue) String() string { return proto.CompactTextString(m) }
func (*TypedValue) ProtoMessage()    {}
func (*TypedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{2}
}

func (m *TypedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedValue.Unmarshal(m, b)
}
func (m *TypedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedValue.Marshal(b, m, deterministic)
}
func (m *TypedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedValue.Merge(m, src)
}
func (m *TypedValue) XXX_Size() int {
	return xxx_messageInfo_TypedValue.Size(m)
}
func (m *TypedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedValue.DiscardUnknown(m)
}

var xxx_messageInfo_TypedValue proto.InternalMessageInfo

type isTypedValue_Value interface {
	isTypedValue_Value()
}

type TypedValue_StringVal struct {
	StringVal string `protobuf:"bytes,1,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type TypedValue_IntVal struct {
	IntVal int64 `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3,oneof"`
}

type TypedValue_UintVal struct {
	UintVal uint64 `protobuf:"varint,3,opt,name=uint_val,json=uintVal,proto3,oneof"`
}

type TypedValue_BoolVal struct {
	BoolVal bool `protobuf:"varint,4,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type TypedValue_BytesVal struct {
	BytesVal []byte `protobuf:"bytes,5,opt,name=bytes_val,json=bytesVal,proto3,oneof"`
}

type TypedValue_FloatVal struct {
	FloatVal float32 `protobuf:"fixed32,6,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type TypedValue_DecimalVal struct {
	DecimalVal *Decimal64 `protobuf:"bytes,7,opt,name=decimal_val,json=decimalVal,proto3,oneof"`
}

type TypedValue_LeaflistVal struct {
	LeaflistVal *ScalarArray `protobuf:"bytes,8,opt,name=leaflist_val,json=leaflistVal,proto3,oneof"`
}

type TypedValue_AnyVal struct {
	AnyVal *any.Any `protobuf:"bytes,9,opt,name=any_val,json=anyVal,proto3,oneof"`
}

type TypedValue_JsonVal struct {
	JsonVal []byte `protobuf:"bytes,10,opt,name=json_val,json=jsonVal,proto3,oneof"`
}

type TypedValue_JsonIetfVal struct {
	JsonIetfVal []byte `protobuf:"bytes,11,opt,name=json_ietf_val,json=jsonIetfVal,proto3,oneof"`
}

type TypedValue_AsciiVal struct {
	AsciiVal string `protobuf:"bytes,12,opt,name=ascii_val,json=asciiVal,proto3,oneof"`
}

type TypedValue_ProtoBytes struct {
	ProtoBytes []byte `protobuf:"bytes,13,opt,name=proto_bytes,json=protoBytes,proto3,oneof"`
}

func (*TypedValue_StringVal) isTypedValue_Value() {}

func (*TypedValue_IntVal) isTypedValue_Value() {}

func (*TypedValue_UintVal) isTypedValue_Value() {}

func (*TypedValue_BoolVal) isTypedValue_Value() {}

func (*TypedValue_BytesVal) isTypedValue_Value() {}

func (*TypedValue_FloatVal) isTypedValue_Value() {}

func (*TypedValue_DecimalVal) isTypedValue_Value() {}

func (*TypedValue_LeaflistVal) isTypedValue_Value() {}

func (*TypedValue_AnyVal) isTypedValue_Value() {}

func (*TypedValue_JsonVal) isTypedValue_Value() {}

func (*TypedValue_JsonIetfVal) isTypedValue_Value() {}

func (*TypedValue_AsciiVal) isTypedValue_Value() {}

func (*TypedValue_ProtoBytes) isTypedValue_Value() {}

func (m *TypedValue) GetValue() isTypedValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TypedValue) GetStringVal() string {
	if x, ok := m.GetValue().(*TypedValue_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (m *TypedValue) GetIntVal() int64 {
	if x, ok := m.GetValue().(*TypedValue_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (m *TypedValue) GetUintVal() uint64 {
	if x, ok := m.GetValue().(*TypedValue_UintVal); ok {
		return x.UintVal
	}
	return 0
}

func (m *TypedValue) GetBoolVal() bool {
	if x, ok := m.GetValue().(*TypedValue_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (m *TypedValue) GetBytesVal() []byte {
	if x, ok := m.GetValue().(*TypedValue_BytesVal); ok {
		return x.BytesVal
	}
	return nil
}

func (m *TypedValue) GetFloatVal() float32 {
	if x, ok := m.GetValue().(*TypedValue_FloatVal); ok {
		return x.FloatVal
	}
	return 0
}

func (m *TypedValue) GetDecimalVal() *Decimal64 {
	if x, ok := m.GetValue().(*TypedValue_DecimalVal); ok {
		return x.DecimalVal
	}
	return nil
}

func (m *TypedValue) GetLeaflistVal() *ScalarArray {
	if x, ok := m.GetValue().(*TypedValue_LeaflistVal); ok {
		return x.LeaflistVal
	}
	return nil
}

func (m *TypedValue) GetAnyVal() *any.Any {
	if x, ok := m.GetValue().(*TypedValue_AnyVal); ok {
		return x.AnyVal
	}
	return nil
}

func (m *TypedValue) GetJsonVal() []byte {
	if x, ok := m.GetValue().(*TypedValue_JsonVal); ok {
		return x.JsonVal
	}
	return nil
}

func (m *TypedValue) GetJsonIetfVal() []byte {
	if x, ok := m.GetValue().(*TypedValue_JsonIetfVal); ok {
		return x.JsonIetfVal
	}
	return nil
}

func (m *TypedValue) GetAsciiVal() string {
	if x, ok := m.GetValue().(*TypedValue_AsciiVal); ok {
		return x.AsciiVal
	}
	return ""
}

func (m *TypedValue) GetProtoBytes() []byte {
	if x, ok := m.GetValue().(*TypedValue_ProtoBytes); ok {
		return x.ProtoBytes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypedValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypedValue_StringVal)(nil),
		(*TypedValue_IntVal)(nil),
		(*TypedValue_UintVal)(nil),
		(*TypedValue_BoolVal)(nil),
		(*TypedValue_BytesVal)(nil),
		(*TypedValue_FloatVal)(nil),
		(*TypedValue_DecimalVal)(nil),
		(*TypedValue_LeaflistVal)(nil),
		(*TypedValue_AnyVal)(nil),
		(*TypedValue_JsonVal)(nil),
		(*TypedValue_JsonIetfVal)(nil),
		(*TypedValue_AsciiVal)(nil),
		(*TypedValue_ProtoBytes)(nil),
	}
}

type Path struct {
	Element              []string    `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"` // Deprecated: Do not use.
	Origin               string      `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Elem                 []*PathElem `protobuf:"bytes,3,rep,name=elem,proto3" json:"elem,omitempty"`
	Target               string      `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{3}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *Path) GetElement() []string {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *Path) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Path) GetElem() []*PathElem {
	if m != nil {
		return m.Elem
	}
	return nil
}

func (m *Path) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type PathElem struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  map[string]string `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PathElem) Reset()         { *m = PathElem{} }
func (m *PathElem) String() string { return proto.CompactTextString(m) }
func (*PathElem) ProtoMessage()    {}
func (*PathElem) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{4}
}

func (m *PathElem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathElem.Unmarshal(m, b)
}
func (m *PathElem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathElem.Marshal(b, m, deterministic)
}
func (m *PathElem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathElem.Merge(m, src)
}
func (m *PathElem) XXX_Size() int {
	return xxx_messageInfo_PathElem.Size(m)
}
func (m *PathElem) XXX_DiscardUnknown() {
	xxx_messageInfo_PathElem.DiscardUnknown(m)
}

var xxx_messageInfo_PathElem proto.InternalMessageInfo

func (m *PathElem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PathElem) GetKey() map[string]string {
	if m != nil {
		return m.Key
	}
	return nil
}

// Deprecated: Do not use.
type Value struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 Encoding `protobuf:"varint,2,opt,name=type,proto3,enum=gnmi.Encoding" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{5}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetType() Encoding {
	if m != nil {
		return m.Type
	}
	return Encoding_JSON
}

// Deprecated: Do not use.
type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Decimal64 struct {
	Digits               int64    `protobuf:"varint,1,opt,name=digits,proto3" json:"digits,omitempty"`
	Precision            uint32   `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Decimal64) Reset()         { *m = Decimal64{} }
func (m *Decimal64) String() string { return proto.CompactTextString(m) }
func (*Decimal64) ProtoMessage()    {}
func (*Decimal64) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{7}
}

func (m *Decimal64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decimal64.Unmarshal(m, b)
}
func (m *Decimal64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decimal64.Marshal(b, m, deterministic)
}
func (m *Decimal64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decimal64.Merge(m, src)
}
func (m *Decimal64) XXX_Size() int {
	return xxx_messageInfo_Decimal64.Size(m)
}
func (m *Decimal64) XXX_DiscardUnknown() {
	xxx_messageInfo_Decimal64.DiscardUnknown(m)
}

var xxx_messageInfo_Decimal64 proto.InternalMessageInfo

func (m *Decimal64) GetDigits() int64 {
	if m != nil {
		return m.Digits
	}
	return 0
}

func (m *Decimal64) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

type ScalarArray struct {
	Element              []*TypedValue `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ScalarArray) Reset()         { *m = ScalarArray{} }
func (m *ScalarArray) String() string { return proto.CompactTextString(m) }
func (*ScalarArray) ProtoMessage()    {}
func (*ScalarArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{8}
}

func (m *ScalarArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarArray.Unmarshal(m, b)
}
func (m *ScalarArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarArray.Marshal(b, m, deterministic)
}
func (m *ScalarArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarArray.Merge(m, src)
}
func (m *ScalarArray) XXX_Size() int {
	return xxx_messageInfo_ScalarArray.Size(m)
}
func (m *ScalarArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarArray.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarArray proto.InternalMessageInfo

func (m *ScalarArray) GetElement() []*TypedValue {
	if m != nil {
		return m.Element
	}
	return nil
}

type SubscribeRequest struct {
	// Types that are valid to be assigned to Request:
	//	*SubscribeRequest_Subscribe
	//	*SubscribeRequest_Poll
	//	*SubscribeRequest_Aliases
	Request              isSubscribeRequest_Request `protobuf_oneof:"request"`
	Extension            []*gnmi_ext.Extension      `protobuf:"bytes,5,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{9}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

type isSubscribeRequest_Request interface {
	isSubscribeRequest_Request()
}

type SubscribeRequest_Subscribe struct {
	Subscribe *SubscriptionList `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeRequest_Poll struct {
	Poll *Poll `protobuf:"bytes,3,opt,name=poll,proto3,oneof"`
}

type SubscribeRequest_Aliases struct {
	Aliases *AliasList `protobuf:"bytes,4,opt,name=aliases,proto3,oneof"`
}

func (*SubscribeRequest_Subscribe) isSubscribeRequest_Request() {}

func (*SubscribeRequest_Poll) isSubscribeRequest_Request() {}

func (*SubscribeRequest_Aliases) isSubscribeRequest_Request() {}

func (m *SubscribeRequest) GetRequest() isSubscribeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SubscribeRequest) GetSubscribe() *SubscriptionList {
	if x, ok := m.GetRequest().(*SubscribeRequest_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *SubscribeRequest) GetPoll() *Poll {
	if x, ok := m.GetRequest().(*SubscribeRequest_Poll); ok {
		return x.Poll
	}
	return nil
}

func (m *SubscribeRequest) GetAliases() *AliasList {
	if x, ok := m.GetRequest().(*SubscribeRequest_Aliases); ok {
		return x.Aliases
	}
	return nil
}

func (m *SubscribeRequest) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubscribeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubscribeRequest_Subscribe)(nil),
		(*SubscribeRequest_Poll)(nil),
		(*SubscribeRequest_Aliases)(nil),
	}
}

type Poll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poll) Reset()         { *m = Poll{} }
func (m *Poll) String() string { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()    {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{10}
}

func (m *Poll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poll.Unmarshal(m, b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return xxx_messageInfo_Poll.Size(m)
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

type SubscribeResponse struct {
	// Types that are valid to be assigned to Response:
	//	*SubscribeResponse_Update
	//	*SubscribeResponse_SyncResponse
	//	*SubscribeResponse_Error
	Response             isSubscribeResponse_Response `protobuf_oneof:"response"`
	Extension            []*gnmi_ext.Extension        `protobuf:"bytes,5,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{11}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type isSubscribeResponse_Response interface {
	isSubscribeResponse_Response()
}

type SubscribeResponse_Update struct {
	Update *Notification `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type SubscribeResponse_SyncResponse struct {
	SyncResponse bool `protobuf:"varint,3,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type SubscribeResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SubscribeResponse_Update) isSubscribeResponse_Response() {}

func (*SubscribeResponse_SyncResponse) isSubscribeResponse_Response() {}

func (*SubscribeResponse_Error) isSubscribeResponse_Response() {}

func (m *SubscribeResponse) GetResponse() isSubscribeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SubscribeResponse) GetUpdate() *Notification {
	if x, ok := m.GetResponse().(*SubscribeResponse_Update); ok {
		return x.Update
	}
	return nil
}

func (m *SubscribeResponse) GetSyncResponse() bool {
	if x, ok := m.GetResponse().(*SubscribeResponse_SyncResponse); ok {
		return x.SyncResponse
	}
	return false
}

// Deprecated: Do not use.
func (m *SubscribeResponse) GetError() *Error {
	if x, ok := m.GetResponse().(*SubscribeResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *SubscribeResponse) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubscribeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubscribeResponse_Update)(nil),
		(*SubscribeResponse_SyncResponse)(nil),
		(*SubscribeResponse_Error)(nil),
	}
}

type SubscriptionList struct {
	Prefix               *Path                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Subscription         []*Subscription       `protobuf:"bytes,2,rep,name=subscription,proto3" json:"subscription,omitempty"`
	UseAliases           bool                  `protobuf:"varint,3,opt,name=use_aliases,json=useAliases,proto3" json:"use_aliases,omitempty"`
	Qos                  *QOSMarking           `protobuf:"bytes,4,opt,name=qos,proto3" json:"qos,omitempty"`
	Mode                 SubscriptionList_Mode `protobuf:"varint,5,opt,name=mode,proto3,enum=gnmi.SubscriptionList_Mode" json:"mode,omitempty"`
	AllowAggregation     bool                  `protobuf:"varint,6,opt,name=allow_aggregation,json=allowAggregation,proto3" json:"allow_aggregation,omitempty"`
	UseModels            []*ModelData          `protobuf:"bytes,7,rep,name=use_models,json=useModels,proto3" json:"use_models,omitempty"`
	Encoding             Encoding              `protobuf:"varint,8,opt,name=encoding,proto3,enum=gnmi.Encoding" json:"encoding,omitempty"`
	UpdatesOnly          bool                  `protobuf:"varint,9,opt,name=updates_only,json=updatesOnly,proto3" json:"updates_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SubscriptionList) Reset()         { *m = SubscriptionList{} }
func (m *SubscriptionList) String() string { return proto.CompactTextString(m) }
func (*SubscriptionList) ProtoMessage()    {}
func (*SubscriptionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{12}
}

func (m *SubscriptionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionList.Unmarshal(m, b)
}
func (m *SubscriptionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionList.Marshal(b, m, deterministic)
}
func (m *SubscriptionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionList.Merge(m, src)
}
func (m *SubscriptionList) XXX_Size() int {
	return xxx_messageInfo_SubscriptionList.Size(m)
}
func (m *SubscriptionList) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionList.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionList proto.InternalMessageInfo

func (m *SubscriptionList) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SubscriptionList) GetSubscription() []*Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *SubscriptionList) GetUseAliases() bool {
	if m != nil {
		return m.UseAliases
	}
	return false
}

func (m *SubscriptionList) GetQos() *QOSMarking {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *SubscriptionList) GetMode() SubscriptionList_Mode {
	if m != nil {
		return m.Mode
	}
	return SubscriptionList_STREAM
}

func (m *SubscriptionList) GetAllowAggregation() bool {
	if m != nil {
		return m.AllowAggregation
	}
	return false
}

func (m *SubscriptionList) GetUseModels() []*ModelData {
	if m != nil {
		return m.UseModels
	}
	return nil
}

func (m *SubscriptionList) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_JSON
}

func (m *SubscriptionList) GetUpdatesOnly() bool {
	if m != nil {
		return m.UpdatesOnly
	}
	return false
}

type Subscription struct {
	Path                 *Path            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 SubscriptionMode `protobuf:"varint,2,opt,name=mode,proto3,enum=gnmi.SubscriptionMode" json:"mode,omitempty"`
	SampleInterval       uint64           `protobuf:"varint,3,opt,name=sample_interval,json=sampleInterval,proto3" json:"sample_interval,omitempty"`
	SuppressRedundant    bool             `protobuf:"varint,4,opt,name=suppress_redundant,json=suppressRedundant,proto3" json:"suppress_redundant,omitempty"`
	HeartbeatInterval    uint64           `protobuf:"varint,5,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{13}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Subscription) GetMode() SubscriptionMode {
	if m != nil {
		return m.Mode
	}
	return SubscriptionMode_TARGET_DEFINED
}

func (m *Subscription) GetSampleInterval() uint64 {
	if m != nil {
		return m.SampleInterval
	}
	return 0
}

func (m *Subscription) GetSuppressRedundant() bool {
	if m != nil {
		return m.SuppressRedundant
	}
	return false
}

func (m *Subscription) GetHeartbeatInterval() uint64 {
	if m != nil {
		return m.HeartbeatInterval
	}
	return 0
}

type QOSMarking struct {
	Marking              uint32   `protobuf:"varint,1,opt,name=marking,proto3" json:"marking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QOSMarking) Reset()         { *m = QOSMarking{} }
func (m *QOSMarking) String() string { return proto.CompactTextString(m) }
func (*QOSMarking) ProtoMessage()    {}
func (*QOSMarking) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{14}
}

func (m *QOSMarking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QOSMarking.Unmarshal(m, b)
}
func (m *QOSMarking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QOSMarking.Marshal(b, m, deterministic)
}
func (m *QOSMarking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QOSMarking.Merge(m, src)
}
func (m *QOSMarking) XXX_Size() int {
	return xxx_messageInfo_QOSMarking.Size(m)
}
func (m *QOSMarking) XXX_DiscardUnknown() {
	xxx_messageInfo_QOSMarking.DiscardUnknown(m)
}

var xxx_messageInfo_QOSMarking proto.InternalMessageInfo

func (m *QOSMarking) GetMarking() uint32 {
	if m != nil {
		return m.Marking
	}
	return 0
}

type Alias struct {
	Path                 *Path    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alias) Reset()         { *m = Alias{} }
func (m *Alias) String() string { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()    {}
func (*Alias) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{15}
}

func (m *Alias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alias.Unmarshal(m, b)
}
func (m *Alias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alias.Marshal(b, m, deterministic)
}
func (m *Alias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alias.Merge(m, src)
}
func (m *Alias) XXX_Size() int {
	return xxx_messageInfo_Alias.Size(m)
}
func (m *Alias) XXX_DiscardUnknown() {
	xxx_messageInfo_Alias.DiscardUnknown(m)
}

var xxx_messageInfo_Alias proto.InternalMessageInfo

func (m *Alias) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Alias) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type AliasList struct {
	Alias                []*Alias `protobuf:"bytes,1,rep,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliasList) Reset()         { *m = AliasList{} }
func (m *AliasList) String() string { return proto.CompactTextString(m) }
func (*AliasList) ProtoMessage()    {}
func (*AliasList) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{16}
}

func (m *AliasList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliasList.Unmarshal(m, b)
}
func (m *AliasList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliasList.Marshal(b, m, deterministic)
}
func (m *AliasList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasList.Merge(m, src)
}
func (m *AliasList) XXX_Size() int {
	return xxx_messageInfo_AliasList.Size(m)
}
func (m *AliasList) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasList.DiscardUnknown(m)
}

var xxx_messageInfo_AliasList proto.InternalMessageInfo

func (m *AliasList) GetAlias() []*Alias {
	if m != nil {
		return m.Alias
	}
	return nil
}

type SetRequest struct {
	Prefix               *Path                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Delete               []*Path               `protobuf:"bytes,2,rep,name=delete,proto3" json:"delete,omitempty"`
	Replace              []*Update             `protobuf:"bytes,3,rep,name=replace,proto3" json:"replace,omitempty"`
	Update               []*Update             `protobuf:"bytes,4,rep,name=update,proto3" json:"update,omitempty"`
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,5,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{17}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SetRequest) GetDelete() []*Path {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *SetRequest) GetReplace() []*Update {
	if m != nil {
		return m.Replace
	}
	return nil
}

func (m *SetRequest) GetUpdate() []*Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *SetRequest) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type SetResponse struct {
	Prefix               *Path                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Response             []*UpdateResult       `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	Message              *Error                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Deprecated: Do not use.
	Timestamp            int64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,5,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{18}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SetResponse) GetResponse() []*UpdateResult {
	if m != nil {
		return m.Response
	}
	return nil
}

// Deprecated: Do not use.
func (m *SetResponse) GetMessage() *Error {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SetResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SetResponse) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type UpdateResult struct {
	Timestamp            int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Deprecated: Do not use.
	Path                 *Path                  `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Message              *Error                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Deprecated: Do not use.
	Op                   UpdateResult_Operation `protobuf:"varint,4,opt,name=op,proto3,enum=gnmi.UpdateResult_Operation" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateResult) Reset()         { *m = UpdateResult{} }
func (m *UpdateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()    {}
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{19}
}

func (m *UpdateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResult.Unmarshal(m, b)
}
func (m *UpdateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResult.Marshal(b, m, deterministic)
}
func (m *UpdateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResult.Merge(m, src)
}
func (m *UpdateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateResult.Size(m)
}
func (m *UpdateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResult proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *UpdateResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UpdateResult) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

// Deprecated: Do not use.
func (m *UpdateResult) GetMessage() *Error {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *UpdateResult) GetOp() UpdateResult_Operation {
	if m != nil {
		return m.Op
	}
	return UpdateResult_INVALID
}

type GetRequest struct {
	Prefix               *Path                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Path                 []*Path               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Type                 GetRequest_DataType   `protobuf:"varint,3,opt,name=type,proto3,enum=gnmi.GetRequest_DataType" json:"type,omitempty"`
	Encoding             Encoding              `protobuf:"varint,5,opt,name=encoding,proto3,enum=gnmi.Encoding" json:"encoding,omitempty"`
	UseModels            []*ModelData          `protobuf:"bytes,6,rep,name=use_models,json=useModels,proto3" json:"use_models,omitempty"`
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,7,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{20}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *GetRequest) GetPath() []*Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *GetRequest) GetType() GetRequest_DataType {
	if m != nil {
		return m.Type
	}
	return GetRequest_ALL
}

func (m *GetRequest) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_JSON
}

func (m *GetRequest) GetUseModels() []*ModelData {
	if m != nil {
		return m.UseModels
	}
	return nil
}

func (m *GetRequest) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type GetResponse struct {
	Notification         []*Notification       `protobuf:"bytes,1,rep,name=notification,proto3" json:"notification,omitempty"`
	Error                *Error                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Deprecated: Do not use.
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,3,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{21}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetNotification() []*Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

// Deprecated: Do not use.
func (m *GetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetResponse) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type CapabilityRequest struct {
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,1,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CapabilityRequest) Reset()         { *m = CapabilityRequest{} }
func (m *CapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*CapabilityRequest) ProtoMessage()    {}
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{22}
}

func (m *CapabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilityRequest.Unmarshal(m, b)
}
func (m *CapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilityRequest.Marshal(b, m, deterministic)
}
func (m *CapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilityRequest.Merge(m, src)
}
func (m *CapabilityRequest) XXX_Size() int {
	return xxx_messageInfo_CapabilityRequest.Size(m)
}
func (m *CapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilityRequest proto.InternalMessageInfo

func (m *CapabilityRequest) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type CapabilityResponse struct {
	SupportedModels      []*ModelData          `protobuf:"bytes,1,rep,name=supported_models,json=supportedModels,proto3" json:"supported_models,omitempty"`
	SupportedEncodings   []Encoding            `protobuf:"varint,2,rep,packed,name=supported_encodings,json=supportedEncodings,proto3,enum=gnmi.Encoding" json:"supported_encodings,omitempty"`
	GNMIVersion          string                `protobuf:"bytes,3,opt,name=gNMI_version,json=gNMIVersion,proto3" json:"gNMI_version,omitempty"`
	Extension            []*gnmi_ext.Extension `protobuf:"bytes,4,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CapabilityResponse) Reset()         { *m = CapabilityResponse{} }
func (m *CapabilityResponse) String() string { return proto.CompactTextString(m) }
func (*CapabilityResponse) ProtoMessage()    {}
func (*CapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{23}
}

func (m *CapabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilityResponse.Unmarshal(m, b)
}
func (m *CapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilityResponse.Marshal(b, m, deterministic)
}
func (m *CapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilityResponse.Merge(m, src)
}
func (m *CapabilityResponse) XXX_Size() int {
	return xxx_messageInfo_CapabilityResponse.Size(m)
}
func (m *CapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilityResponse proto.InternalMessageInfo

func (m *CapabilityResponse) GetSupportedModels() []*ModelData {
	if m != nil {
		return m.SupportedModels
	}
	return nil
}

func (m *CapabilityResponse) GetSupportedEncodings() []Encoding {
	if m != nil {
		return m.SupportedEncodings
	}
	return nil
}

func (m *CapabilityResponse) GetGNMIVersion() string {
	if m != nil {
		return m.GNMIVersion
	}
	return ""
}

func (m *CapabilityResponse) GetExtension() []*gnmi_ext.Extension {
	if m != nil {
		return m.Extension
	}
	return nil
}

type ModelData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Organization         string   `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelData) Reset()         { *m = ModelData{} }
func (m *ModelData) String() string { return proto.CompactTextString(m) }
func (*ModelData) ProtoMessage()    {}
func (*ModelData) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d884bf56a06d0, []int{24}
}

func (m *ModelData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelData.Unmarshal(m, b)
}
func (m *ModelData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelData.Marshal(b, m, deterministic)
}
func (m *ModelData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelData.Merge(m, src)
}
func (m *ModelData) XXX_Size() int {
	return xxx_messageInfo_ModelData.Size(m)
}
func (m *ModelData) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelData.DiscardUnknown(m)
}

var xxx_messageInfo_ModelData proto.InternalMessageInfo

func (m *ModelData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelData) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ModelData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

var E_GnmiService = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "gnmi.gnmi_service",
	Tag:           "bytes,1001,opt,name=gnmi_service",
	Filename:      "github.com/openconfig/gnmi/proto/gnmi/gnmi.proto",
}

func init() {
	proto.RegisterEnum("gnmi.Encoding", Encoding_name, Encoding_value)
	proto.RegisterEnum("gnmi.SubscriptionMode", SubscriptionMode_name, SubscriptionMode_value)
	proto.RegisterEnum("gnmi.SubscriptionList_Mode", SubscriptionList_Mode_name, SubscriptionList_Mode_value)
	proto.RegisterEnum("gnmi.UpdateResult_Operation", UpdateResult_Operation_name, UpdateResult_Operation_value)
	proto.RegisterEnum("gnmi.GetRequest_DataType", GetRequest_DataType_name, GetRequest_DataType_value)
	proto.RegisterType((*Notification)(nil), "gnmi.Notification")
	proto.RegisterType((*Update)(nil), "gnmi.Update")
	proto.RegisterType((*TypedValue)(nil), "gnmi.TypedValue")
	proto.RegisterType((*Path)(nil), "gnmi.Path")
	proto.RegisterType((*PathElem)(nil), "gnmi.PathElem")
	proto.RegisterMapType((map[string]string)(nil), "gnmi.PathElem.KeyEntry")
	proto.RegisterType((*Value)(nil), "gnmi.Value")
	proto.RegisterType((*Error)(nil), "gnmi.Error")
	proto.RegisterType((*Decimal64)(nil), "gnmi.Decimal64")
	proto.RegisterType((*ScalarArray)(nil), "gnmi.ScalarArray")
	proto.RegisterType((*SubscribeRequest)(nil), "gnmi.SubscribeRequest")
	proto.RegisterType((*Poll)(nil), "gnmi.Poll")
	proto.RegisterType((*SubscribeResponse)(nil), "gnmi.SubscribeResponse")
	proto.RegisterType((*SubscriptionList)(nil), "gnmi.SubscriptionList")
	proto.RegisterType((*Subscription)(nil), "gnmi.Subscription")
	proto.RegisterType((*QOSMarking)(nil), "gnmi.QOSMarking")
	proto.RegisterType((*Alias)(nil), "gnmi.Alias")
	proto.RegisterType((*AliasList)(nil), "gnmi.AliasList")
	proto.RegisterType((*SetRequest)(nil), "gnmi.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "gnmi.SetResponse")
	proto.RegisterType((*UpdateResult)(nil), "gnmi.UpdateResult")
	proto.RegisterType((*GetRequest)(nil), "gnmi.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "gnmi.GetResponse")
	proto.RegisterType((*CapabilityRequest)(nil), "gnmi.CapabilityRequest")
	proto.RegisterType((*CapabilityResponse)(nil), "gnmi.CapabilityResponse")
	proto.RegisterType((*ModelData)(nil), "gnmi.ModelData")
	proto.RegisterExtension(E_GnmiService)
}

func init() {
	proto.RegisterFile("github.com/openconfig/gnmi/proto/gnmi/gnmi.proto", fileDescriptor_178d884bf56a06d0)
}

var fileDescriptor_178d884bf56a06d0 = []byte{
	// 1953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcf, 0x72, 0xe3, 0xc6,
	0xd1, 0x27, 0x08, 0xfe, 0x43, 0x93, 0xd2, 0x52, 0x63, 0x97, 0xcd, 0x95, 0xf7, 0xb3, 0xb9, 0x28,
	0x7b, 0x4d, 0xcb, 0x36, 0xb5, 0x9f, 0x92, 0x52, 0x9c, 0x4d, 0x39, 0x31, 0x25, 0x41, 0x12, 0x13,
	0x8a, 0x54, 0x86, 0xf4, 0x56, 0xe5, 0x90, 0x62, 0x8d, 0xc8, 0x11, 0x17, 0x31, 0x08, 0xc0, 0xc0,
	0x70, 0xb3, 0xcc, 0x2d, 0xcf, 0x90, 0x07, 0xc8, 0x6b, 0xe4, 0x11, 0x52, 0xc9, 0x25, 0x97, 0x54,
	0x4e, 0x39, 0xa4, 0x72, 0x48, 0x52, 0x79, 0x89, 0x54, 0xcf, 0x0c, 0x00, 0x72, 0xc9, 0xad, 0xd5,
	0xfa, 0xc2, 0x9a, 0xe9, 0x5f, 0x77, 0x63, 0x7a, 0xba, 0xe7, 0xd7, 0x4d, 0x78, 0x3c, 0x73, 0xc5,
	0xb3, 0xc5, 0x4d, 0x7b, 0x12, 0xcc, 0x0f, 0x83, 0x90, 0xfb, 0x93, 0xc0, 0xbf, 0x75, 0x67, 0x87,
	0x33, 0x7f, 0xee, 0x1e, 0x86, 0x51, 0x20, 0x02, 0xb5, 0xc4, 0x9f, 0xb6, 0xdc, 0x93, 0x02, 0xae,
	0xf7, 0xef, 0xcf, 0x82, 0x60, 0xe6, 0x71, 0xa5, 0x73, 0xb3, 0xb8, 0x3d, 0x64, 0xfe, 0x52, 0x29,
	0xec, 0x37, 0x5f, 0x86, 0xa6, 0x3c, 0x9e, 0x44, 0x6e, 0x28, 0x82, 0x48, 0x6b, 0x7c, 0x71, 0xa7,
	0x8f, 0x8e, 0xf9, 0x0b, 0x91, 0x2e, 0x94, 0xa5, 0xfd, 0x47, 0x03, 0x6a, 0xfd, 0x40, 0xb8, 0xb7,
	0xee, 0x84, 0x09, 0x37, 0xf0, 0xc9, 0x03, 0xb0, 0x84, 0x3b, 0xe7, 0xb1, 0x60, 0xf3, 0xb0, 0x61,
	0x34, 0x8d, 0x96, 0x49, 0x33, 0x01, 0xb1, 0xa1, 0x14, 0x46, 0xfc, 0xd6, 0x7d, 0xd1, 0xc8, 0x37,
	0x8d, 0x56, 0xf5, 0x08, 0xda, 0x32, 0x90, 0x6b, 0x26, 0x9e, 0x51, 0x8d, 0x90, 0xb7, 0xa1, 0xc8,
	0x3c, 0x97, 0xc5, 0x0d, 0xb3, 0x69, 0xb4, 0x2c, 0xaa, 0x36, 0xe4, 0x43, 0x28, 0x2d, 0xc2, 0x29,
	0x13, 0xbc, 0x51, 0x68, 0x9a, 0xad, 0xea, 0x51, 0x4d, 0x59, 0x7e, 0x2d, 0x65, 0x54, 0x63, 0xe8,
	0x7f, 0xca, 0x3d, 0x2e, 0x78, 0xa3, 0x28, 0xb5, 0xd6, 0xfc, 0x2b, 0x84, 0xbc, 0x03, 0x25, 0x26,
	0x82, 0xb9, 0x3b, 0x69, 0x94, 0x9a, 0x46, 0xab, 0x42, 0xf5, 0xce, 0xfe, 0x9d, 0x01, 0x25, 0xe5,
	0x8e, 0xbc, 0x0f, 0x85, 0x90, 0x89, 0x67, 0xf2, 0xfc, 0xeb, 0x4e, 0xa4, 0x9c, 0x7c, 0x04, 0xc5,
	0xe7, 0xcc, 0x5b, 0x70, 0x1d, 0x45, 0x55, 0x29, 0x3c, 0x45, 0xd1, 0x49, 0xbe, 0x61, 0x50, 0x85,
	0x12, 0x1b, 0xcc, 0xe7, 0xcc, 0x93, 0x71, 0x54, 0x8f, 0xea, 0x4a, 0x69, 0xb4, 0x0c, 0xf9, 0x54,
	0x6a, 0x52, 0x04, 0xc9, 0xfb, 0x00, 0xd3, 0x45, 0xe8, 0xe1, 0xf5, 0xf1, 0xb8, 0x51, 0x68, 0x1a,
	0xad, 0x1d, 0xba, 0x22, 0xb1, 0xff, 0x6b, 0x02, 0x64, 0x36, 0xe4, 0x03, 0x80, 0x58, 0x44, 0xae,
	0x3f, 0x1b, 0xa3, 0x67, 0x3c, 0x9f, 0x75, 0x99, 0xa3, 0x96, 0x92, 0x3d, 0x65, 0x1e, 0xb9, 0x0f,
	0x65, 0xd7, 0x17, 0x12, 0xc5, 0xc3, 0x99, 0x97, 0x39, 0x5a, 0x72, 0x7d, 0x81, 0xd0, 0x7b, 0x50,
	0x59, 0x24, 0x18, 0x9e, 0xa9, 0x70, 0x99, 0xa3, 0xe5, 0x45, 0x06, 0xde, 0x04, 0x81, 0x27, 0x41,
	0x3c, 0x45, 0x05, 0x41, 0x94, 0x20, 0xf8, 0x7f, 0x60, 0xdd, 0x2c, 0x05, 0x8f, 0x25, 0x5a, 0x6c,
	0x1a, 0xad, 0xda, 0x65, 0x8e, 0x56, 0xa4, 0x48, 0xc3, 0xb7, 0x5e, 0xc0, 0x94, 0x67, 0xbc, 0xd4,
	0x3c, 0xc2, 0x52, 0x84, 0xf0, 0x11, 0x54, 0xa7, 0x7c, 0xe2, 0xce, 0x99, 0xf2, 0x5e, 0x96, 0xd7,
	0x71, 0x4f, 0x5d, 0xc7, 0x99, 0x02, 0x8e, 0xbf, 0x7f, 0x99, 0xa3, 0xa0, 0xb5, 0xd0, 0xe6, 0x18,
	0x6a, 0x1e, 0x67, 0xb7, 0x9e, 0x1b, 0x2b, 0xaf, 0x15, 0x69, 0xb4, 0xa7, 0x8c, 0x86, 0x13, 0xe6,
	0xb1, 0xa8, 0x13, 0x45, 0x6c, 0x79, 0x99, 0xa3, 0xd5, 0x44, 0x11, 0xed, 0x0e, 0xa1, 0xcc, 0xfc,
	0xa5, 0x34, 0xb1, 0xa4, 0xc9, 0xdb, 0x6d, 0x55, 0xfd, 0xed, 0xa4, 0xfa, 0xdb, 0x1d, 0x1f, 0xad,
	0x4a, 0xcc, 0x5f, 0xea, 0xb8, 0x7f, 0x15, 0x07, 0xbe, 0xb4, 0x00, 0x1d, 0x59, 0x19, 0x25, 0x08,
	0x7e, 0x08, 0x3b, 0x12, 0x74, 0xb9, 0xb8, 0x95, 0x1a, 0x55, 0xad, 0x51, 0x45, 0x71, 0x97, 0x8b,
	0x5b, 0x1d, 0x3e, 0x8b, 0x27, 0xae, 0x2b, 0x35, 0x6a, 0x3a, 0x25, 0x15, 0x29, 0x42, 0xf8, 0x21,
	0x54, 0xe5, 0xb7, 0xc7, 0xf2, 0xbe, 0x1a, 0x3b, 0xda, 0x05, 0x48, 0xe1, 0x09, 0xca, 0x4e, 0xca,
	0xba, 0x9e, 0xec, 0x17, 0x50, 0xc0, 0x32, 0x23, 0x0f, 0xa0, 0xcc, 0x3d, 0x3e, 0xe7, 0xbe, 0x68,
	0x18, 0x4d, 0xb3, 0x65, 0xc9, 0xaa, 0x4a, 0x44, 0x58, 0xc1, 0x41, 0xe4, 0xce, 0x5c, 0x5f, 0xa6,
	0xd8, 0xa2, 0x7a, 0x47, 0x6c, 0x28, 0xa0, 0x4a, 0xc3, 0x94, 0xb5, 0xbf, 0x9b, 0x95, 0xad, 0xe3,
	0xf1, 0x39, 0x95, 0x18, 0xda, 0x0a, 0x16, 0xcd, 0xb8, 0x90, 0x59, 0xb6, 0xa8, 0xde, 0xd9, 0xbf,
	0x35, 0xa0, 0x92, 0xa8, 0x12, 0x02, 0x05, 0x9f, 0xcd, 0xb9, 0xaa, 0x2f, 0x2a, 0xd7, 0xe4, 0x13,
	0x30, 0xbf, 0xe1, 0xcb, 0x46, 0x5e, 0xfa, 0x7e, 0x77, 0xdd, 0x77, 0xfb, 0x67, 0x7c, 0xe9, 0xf8,
	0x22, 0x5a, 0x52, 0xd4, 0xd9, 0x3f, 0x86, 0x4a, 0x22, 0x20, 0x75, 0x65, 0xa6, 0x3c, 0xe1, 0x12,
	0xdf, 0x77, 0xf6, 0x78, 0x2c, 0xfd, 0x56, 0x9e, 0xe4, 0xbf, 0x30, 0x6c, 0x07, 0x8a, 0xaa, 0xca,
	0x53, 0x15, 0x34, 0xab, 0x65, 0xcf, 0xa9, 0x20, 0x96, 0xa1, 0xb2, 0xdb, 0x4d, 0xc2, 0x73, 0xfc,
	0x49, 0x30, 0x75, 0xfd, 0x19, 0x95, 0xd8, 0x93, 0x7c, 0xc3, 0xb0, 0x27, 0x50, 0x74, 0xa2, 0x28,
	0x88, 0x30, 0x8c, 0x49, 0x30, 0x55, 0x5e, 0x76, 0xa8, 0x5c, 0x93, 0x06, 0x94, 0xe7, 0x3c, 0x8e,
	0xd9, 0x2c, 0xf9, 0x7e, 0xb2, 0x25, 0x2d, 0x28, 0x4c, 0x99, 0x60, 0xfa, 0xb9, 0x6e, 0xad, 0x1b,
	0x2a, 0x35, 0xe4, 0x47, 0x3a, 0x60, 0xa5, 0xb5, 0x8b, 0x97, 0x3a, 0x75, 0x67, 0xae, 0x88, 0x35,
	0xe3, 0xe9, 0x1d, 0x92, 0x61, 0x18, 0xf1, 0x89, 0x1b, 0xbb, 0x81, 0xca, 0xd5, 0x0e, 0xcd, 0x04,
	0xf6, 0x0f, 0xa1, 0xba, 0x52, 0xc9, 0xe4, 0x60, 0x3d, 0xe7, 0xdb, 0x18, 0x23, 0x51, 0xb0, 0xff,
	0x66, 0x40, 0x7d, 0xb8, 0xb8, 0x41, 0x1a, 0xbf, 0xe1, 0x94, 0x7f, 0xbb, 0xe0, 0xb1, 0x20, 0xc7,
	0x60, 0xc5, 0x89, 0x4c, 0x53, 0xd7, 0x3b, 0xfa, 0xc1, 0x28, 0x71, 0x88, 0x0c, 0xdd, 0x73, 0x63,
	0x21, 0x29, 0x23, 0x51, 0x25, 0x4d, 0x28, 0x84, 0x81, 0x97, 0xf0, 0x54, 0xc2, 0x76, 0x81, 0xe7,
	0x5d, 0xe6, 0xa8, 0x44, 0xc8, 0xa7, 0x50, 0x96, 0x2c, 0xac, 0x19, 0x2a, 0x7d, 0xbd, 0x1d, 0x14,
	0x6a, 0x87, 0x89, 0x06, 0xf9, 0x7f, 0xb0, 0xf8, 0x0b, 0xc1, 0x7d, 0x19, 0xb4, 0xa2, 0xe1, 0xb7,
	0xda, 0x69, 0xdb, 0x70, 0x12, 0x88, 0x66, 0x5a, 0x27, 0x16, 0x94, 0x23, 0x15, 0x84, 0x5d, 0x82,
	0x02, 0x7e, 0xda, 0xfe, 0x8b, 0x01, 0x7b, 0x2b, 0x11, 0xc6, 0x61, 0xe0, 0xc7, 0x9c, 0x7c, 0x96,
	0x76, 0x01, 0x15, 0x1f, 0x51, 0xe7, 0x58, 0xed, 0x40, 0xf8, 0xb6, 0x75, 0x37, 0xf8, 0x08, 0x76,
	0xe2, 0xa5, 0x3f, 0x19, 0x47, 0xda, 0x5c, 0x46, 0x88, 0xc4, 0x56, 0x43, 0x71, 0xea, 0xf4, 0x63,
	0x28, 0x72, 0xac, 0x17, 0x1d, 0x9b, 0x66, 0x73, 0x59, 0x42, 0xf8, 0xee, 0x2e, 0x73, 0x54, 0xe1,
	0xdf, 0x25, 0x32, 0x80, 0x4a, 0xf2, 0x75, 0xfb, 0x0f, 0x66, 0x9a, 0xb4, 0x34, 0x13, 0x2b, 0x1d,
	0xd1, 0x78, 0x65, 0x47, 0x3c, 0x86, 0x5a, 0xbc, 0x62, 0xa7, 0xdf, 0x20, 0xd9, 0xcc, 0x2d, 0x5d,
	0xd3, 0x23, 0x1f, 0x40, 0x75, 0x11, 0xf3, 0x71, 0x92, 0x3a, 0x19, 0x3d, 0x85, 0x45, 0xcc, 0x3b,
	0x3a, 0x55, 0x36, 0x98, 0xdf, 0x06, 0x49, 0x4e, 0x75, 0xb9, 0xfd, 0x7c, 0x30, 0xbc, 0x62, 0xd1,
	0x37, 0xf8, 0xa4, 0x10, 0x24, 0x87, 0x50, 0x98, 0xe3, 0x23, 0x2a, 0xca, 0x57, 0xf7, 0xde, 0xf6,
	0x82, 0x6a, 0x5f, 0x05, 0x53, 0x4e, 0xa5, 0x22, 0xf9, 0x14, 0xf6, 0x98, 0xe7, 0x05, 0xbf, 0x1e,
	0xb3, 0xd9, 0x2c, 0xe2, 0x33, 0x99, 0x14, 0xdd, 0x6a, 0xeb, 0x12, 0xe8, 0x64, 0x72, 0xd2, 0x06,
	0x3c, 0xcf, 0x18, 0x0d, 0xbd, 0xb8, 0x51, 0x96, 0x81, 0xe9, 0xe2, 0x42, 0x97, 0xde, 0x19, 0x13,
	0x8c, 0x5a, 0x8b, 0x98, 0xcb, 0x5d, 0x4c, 0x0e, 0xa0, 0xc2, 0xf5, 0x8b, 0x97, 0x3d, 0x61, 0x93,
	0x07, 0x52, 0x9c, 0x3c, 0x84, 0x9a, 0x2a, 0x84, 0x78, 0x1c, 0xf8, 0xde, 0x52, 0x36, 0x84, 0x0a,
	0xad, 0x6a, 0xd9, 0xc0, 0xf7, 0x96, 0xf6, 0x23, 0x28, 0xa0, 0x63, 0x02, 0x50, 0x1a, 0x8e, 0xa8,
	0xd3, 0xb9, 0xaa, 0xe7, 0x48, 0x05, 0x0a, 0x83, 0xfe, 0xa9, 0x53, 0x37, 0x70, 0x75, 0x3d, 0xe8,
	0xf5, 0xea, 0x79, 0xfb, 0x1f, 0x06, 0xd4, 0x56, 0x63, 0x7e, 0xed, 0x84, 0x70, 0xa0, 0x6f, 0x4d,
	0x71, 0xd5, 0x96, 0x67, 0xb8, 0x72, 0x61, 0x1f, 0xc3, 0xbd, 0x98, 0xcd, 0x43, 0x8f, 0x8f, 0x5d,
	0x5f, 0xf0, 0x28, 0x6d, 0xcf, 0x74, 0x57, 0x89, 0xbb, 0x5a, 0x4a, 0x3e, 0x07, 0x12, 0x2f, 0xc2,
	0x30, 0xe2, 0x71, 0x3c, 0x8e, 0xf8, 0x74, 0xe1, 0x4f, 0x99, 0xaf, 0x78, 0xbc, 0x42, 0xf7, 0x12,
	0x84, 0x26, 0x00, 0xaa, 0x3f, 0xe3, 0x2c, 0x12, 0x37, 0x9c, 0x89, 0xcc, 0x75, 0x51, 0xba, 0xde,
	0x4b, 0x91, 0xc4, 0xbb, 0xfd, 0x08, 0x20, 0xcb, 0xbd, 0xe4, 0x49, 0xb5, 0xd4, 0xf4, 0x99, 0x6c,
	0xed, 0x2f, 0xa1, 0x28, 0xeb, 0xe7, 0xb5, 0x77, 0x90, 0x0e, 0x72, 0xf9, 0x95, 0x41, 0xce, 0x6e,
	0x83, 0x95, 0xd2, 0x06, 0x79, 0x98, 0xa8, 0x28, 0xc6, 0xab, 0xae, 0xd0, 0x4a, 0xa2, 0xff, 0x57,
	0x03, 0x60, 0xc8, 0x45, 0x42, 0x72, 0x77, 0x79, 0x2f, 0xd9, 0x14, 0x98, 0x7f, 0xe5, 0x14, 0xf8,
	0x08, 0x29, 0x27, 0xf4, 0xd8, 0x84, 0xeb, 0x76, 0xb9, 0x3e, 0x50, 0x26, 0xe0, 0x1d, 0xe7, 0xce,
	0x37, 0x67, 0x06, 0xfb, 0xef, 0x06, 0x54, 0x65, 0x5c, 0x9a, 0x85, 0xee, 0x12, 0x58, 0x3b, 0x63,
	0x93, 0x75, 0x12, 0xd0, 0xc7, 0xe1, 0xf1, 0xc2, 0x13, 0x34, 0xd5, 0x21, 0x9f, 0x64, 0xcd, 0xce,
	0xdc, 0xca, 0x6d, 0x59, 0xf7, 0x5b, 0x9b, 0xdb, 0x0b, 0x2f, 0xcf, 0xed, 0xdf, 0x21, 0xbe, 0x7f,
	0x1b, 0x50, 0x5b, 0x3d, 0x16, 0x69, 0x6e, 0xfc, 0x33, 0x90, 0x27, 0x58, 0xf9, 0x4a, 0x52, 0x50,
	0xf9, 0x57, 0x14, 0xd4, 0x1b, 0x84, 0xf3, 0x19, 0xe4, 0x03, 0x15, 0xc7, 0xee, 0xd1, 0x83, 0xcd,
	0x3b, 0x6a, 0x0f, 0x42, 0x1e, 0x49, 0x06, 0xa2, 0xf9, 0x20, 0xb4, 0xbf, 0x04, 0x2b, 0x15, 0x90,
	0x2a, 0x94, 0xbb, 0xfd, 0xa7, 0x9d, 0x5e, 0xf7, 0xac, 0x9e, 0x43, 0x62, 0x38, 0x73, 0x7a, 0xce,
	0x08, 0xe9, 0xa0, 0x0a, 0x65, 0xea, 0x5c, 0xf7, 0x3a, 0xa7, 0x4e, 0x3d, 0x8f, 0xc0, 0xd7, 0xd7,
	0x67, 0x9d, 0x91, 0x53, 0x37, 0xed, 0x3f, 0xe7, 0x01, 0x2e, 0xde, 0xac, 0x44, 0xb3, 0x50, 0xcd,
	0xad, 0xa1, 0x7e, 0xae, 0x67, 0x1d, 0x53, 0x46, 0x70, 0x5f, 0xe1, 0xd9, 0x37, 0xda, 0xc8, 0x8b,
	0x38, 0x18, 0xa8, 0xb1, 0x67, 0x8d, 0x16, 0x8b, 0xaf, 0xa1, 0xc5, 0x75, 0xca, 0x2d, 0xbd, 0x96,
	0x72, 0xd7, 0x72, 0x5f, 0xbe, 0x53, 0xee, 0x7f, 0x04, 0x95, 0xe4, 0x80, 0xa4, 0x0c, 0x66, 0xa7,
	0xd7, 0x53, 0x57, 0x79, 0x3a, 0xe8, 0x9f, 0x77, 0x2f, 0xea, 0x06, 0xb1, 0xa0, 0x38, 0x1c, 0xe1,
	0xe5, 0xe5, 0xc9, 0x3d, 0xa8, 0x0e, 0xae, 0x1d, 0xda, 0x19, 0x75, 0x07, 0xfd, 0x4e, 0xaf, 0x6e,
	0xda, 0xbf, 0x37, 0xa0, 0x7a, 0xb1, 0xf2, 0x30, 0x8e, 0xa1, 0xe6, 0xaf, 0xf4, 0x77, 0x4d, 0x15,
	0x5b, 0x3a, 0x3f, 0x5d, 0xd3, 0xc3, 0x3f, 0x69, 0xaa, 0xad, 0xe7, 0xb7, 0xd7, 0xca, 0xb6, 0xa6,
	0x6e, 0xde, 0x29, 0xbc, 0x73, 0xd8, 0x3b, 0x65, 0x21, 0xbb, 0x71, 0x3d, 0x57, 0x2c, 0x93, 0xac,
	0xaf, 0xf9, 0x31, 0xee, 0xe4, 0xe7, 0x5f, 0x06, 0x90, 0x55, 0x47, 0x3a, 0xe0, 0x27, 0x50, 0x47,
	0x32, 0x0f, 0x22, 0xc1, 0xa7, 0x49, 0x9a, 0x8c, 0xed, 0x69, 0xba, 0x97, 0x2a, 0xea, 0x64, 0xfd,
	0x04, 0xde, 0xca, 0x6c, 0x93, 0x94, 0xc7, 0xb2, 0xcc, 0x36, 0x6b, 0x82, 0xa4, 0xaa, 0x89, 0x28,
	0xc6, 0xa6, 0x39, 0xeb, 0x5f, 0x75, 0xc7, 0xcf, 0x79, 0xa4, 0x6f, 0x04, 0xb9, 0xbb, 0x8a, 0xb2,
	0xa7, 0x4a, 0xb4, 0x1e, 0x69, 0xe1, 0x4e, 0x91, 0xfe, 0x12, 0xac, 0xf4, 0xd0, 0x5b, 0xff, 0x5d,
	0xd8, 0x50, 0x0b, 0xa2, 0x19, 0xf3, 0xdd, 0xdf, 0x30, 0x91, 0x0c, 0xcb, 0x16, 0x5d, 0x93, 0x61,
	0x4b, 0x5a, 0x3f, 0x55, 0xb2, 0x3d, 0x38, 0x83, 0x4a, 0x12, 0x01, 0x36, 0xed, 0x9f, 0x0e, 0x07,
	0xfd, 0x7a, 0x0e, 0x8b, 0xec, 0xe4, 0x17, 0x23, 0x67, 0xa8, 0xea, 0xed, 0x9a, 0x0e, 0x46, 0x83,
	0x7a, 0x1e, 0x97, 0x9d, 0xe1, 0x69, 0xb7, 0x5b, 0x37, 0xc9, 0x0e, 0x58, 0xa8, 0x3a, 0xee, 0x3a,
	0xa3, 0xf3, 0x7a, 0xe1, 0xa0, 0xb3, 0x3e, 0x9e, 0xc9, 0xc1, 0x80, 0xc0, 0xee, 0xa8, 0x43, 0x2f,
	0x9c, 0xd1, 0xf8, 0xcc, 0x39, 0xef, 0xf6, 0x1d, 0xe4, 0x84, 0x1d, 0xb0, 0x06, 0xfd, 0xf1, 0xe9,
	0x65, 0xa7, 0x7f, 0x81, 0xb4, 0x80, 0xb3, 0x43, 0xe7, 0xea, 0xba, 0xe7, 0xd4, 0xf3, 0x47, 0xff,
	0x34, 0xa0, 0x80, 0x57, 0x45, 0x3a, 0x50, 0x4b, 0x33, 0xeb, 0xf2, 0x98, 0xe8, 0x3f, 0x4c, 0x1b,
	0x65, 0xb3, 0xdf, 0xd8, 0x04, 0x74, 0x19, 0x1c, 0x80, 0x79, 0xc1, 0x05, 0xa9, 0xbf, 0xfc, 0xf6,
	0xf7, 0xf7, 0x56, 0x24, 0x99, 0xee, 0x30, 0xd3, 0x1d, 0x6e, 0xe8, 0xae, 0x36, 0x9a, 0xaf, 0xc0,
	0x4a, 0x07, 0x6b, 0xb2, 0x3e, 0x99, 0xa4, 0xff, 0x25, 0xf6, 0xdf, 0xdd, 0x90, 0x2b, 0xeb, 0x96,
	0xf1, 0xd8, 0x78, 0xf2, 0x15, 0xd4, 0x64, 0xba, 0x63, 0x1e, 0x3d, 0x77, 0x27, 0x9c, 0x3c, 0xd8,
	0xf8, 0xaf, 0x74, 0xee, 0x7a, 0x7c, 0x20, 0x6f, 0x31, 0x6e, 0xfc, 0xa7, 0xac, 0x4b, 0xc8, 0x9f,
	0xbb, 0x43, 0x65, 0x71, 0x52, 0xf9, 0xd3, 0x8f, 0x8b, 0x8f, 0xdb, 0x3f, 0x68, 0x3f, 0xbe, 0x29,
	0x49, 0x9b, 0xef, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x4b, 0x47, 0x24, 0xf8, 0x12, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GNMIClient is the client API for GNMI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GNMIClient interface {
	Capabilities(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (GNMI_SubscribeClient, error)
}

type gNMIClient struct {
	cc *grpc.ClientConn
}

func NewGNMIClient(cc *grpc.ClientConn) GNMIClient {
	return &gNMIClient{cc}
}

func (c *gNMIClient) Capabilities(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error) {
	out := new(CapabilityResponse)
	err := c.cc.Invoke(ctx, "/gnmi.gNMI/Capabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/gnmi.gNMI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMIClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/gnmi.gNMI/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMIClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (GNMI_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GNMI_serviceDesc.Streams[0], "/gnmi.gNMI/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &gNMISubscribeClient{stream}
	return x, nil
}

type GNMI_SubscribeClient interface {
	Send(*SubscribeRequest) error
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type gNMISubscribeClient struct {
	grpc.ClientStream
}

func (x *gNMISubscribeClient) Send(m *SubscribeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gNMISubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GNMIServer is the server API for GNMI service.
type GNMIServer interface {
	Capabilities(context.Context, *CapabilityRequest) (*CapabilityResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Subscribe(GNMI_SubscribeServer) error
}

func RegisterGNMIServer(s *grpc.Server, srv GNMIServer) {
	s.RegisterService(&_GNMI_serviceDesc, srv)
}

func _GNMI_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMIServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnmi.gNMI/Capabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMIServer).Capabilities(ctx, req.(*CapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnmi.gNMI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMIServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMI_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMIServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnmi.gNMI/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMIServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMI_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GNMIServer).Subscribe(&gNMISubscribeServer{stream})
}

type GNMI_SubscribeServer interface {
	Send(*SubscribeResponse) error
	Recv() (*SubscribeRequest, error)
	grpc.ServerStream
}

type gNMISubscribeServer struct {
	grpc.ServerStream
}

func (x *gNMISubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gNMISubscribeServer) Recv() (*SubscribeRequest, error) {
	m := new(SubscribeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GNMI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnmi.gNMI",
	HandlerType: (*GNMIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _GNMI_Capabilities_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GNMI_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _GNMI_Set_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _GNMI_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/openconfig/gnmi/proto/gnmi/gnmi.proto",
}
